[package]
name = "html2pdf"
version = "0.8.3"
edition = "2021"
rust-version = "1.85"
authors = ["Igor Laborie <ilaborie@gmail.com>"]
description = "Convert HTML to PDF using a Headless Chrome browser"
license = "Apache-2.0 OR MIT"
repository = "https://github.com/ilaborie/html2pdf"
documentation = "https://docs.rs/html2pdf"
homepage = "https://github.com/ilaborie/html2pdf"
keywords = ["cli", "pdf"]
categories = ["command-line-utilities", "encoding"]

[dependencies]
chromiumoxide = "0.9.1"
clap = { version = "4.6.6", features = ["derive"] }
derive_more = { version = "2.1.1", features = ["from", "error", "display"] }
dunce = "1.0.5"
futures = "0.3.34"
humantime = "2.4.0"
tempfile = "3.27.0"
tokio = { version = "1.53.1", features = ["macros", "rt-multi-thread", "time"] }
tracing = "0.1.44"
tracing-subscriber = { version = "0.3.23", features = ["env-filter", "fmt"] }

[dev-dependencies]
assert2 = "0.4.0"
rstest = "0.26.1"
tokio = { version = "1.53.1", features = ["macros", "rt-multi-thread"] }

# The profile that 'dist' will build with
[profile.dist]
inherits = "release"
lto = "thin"
